Audio task
Nick-VanEssen/pnw-ova pull request #14
Opened 2023-11-26 20:33 UTC by doudar

- Added LED diagnostic to PDM Mic.
- Added memory debugging.
- Added PDM mic task. 
- Added pdm.oStream output for raw audio amplitude retrieval.

2023-11-27 03:37 UTC, Nick-VanEssen requested changes

2023-11-27 03:37 UTC, Nick-VanEssen commented on src/main.cpp
>      mailResults.send();
comment out
```suggestion
    // mailResults.send();
```

2023-11-29 21:26 UTC, Matt-VanEssen approved these changes

2023-11-29 21:37 UTC, Nick-VanEssen approved these changes

2023-11-29 21:37 UTC, merged